---
title: "Research Topics"
author: "The Repos - Jeffrey Bohrer, Alexandra Green, Anna Zhang, Kevin Lee"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

## Research Topic 1

Our first research topic is on autism, specifically by building a model to better predict autism early on. Because autism is extremely hard to diagnose, we recognize that it is important to develop a better test to ensure that those affected by it procure the treatment they need. The primary audience would likely be healthcare professionals and individuals who suspect they (or someone close to them) have autism and are attempting to more accurately assess their risk of having autism. Potential research questions include:

1.  Can a simplified set of features, especially from just the screening questions, be used to classify autistic individuals early on?
2.  Are there certain individual characteristics (e.g., age, gender, family history) that significantly influence ASD detection?
3.  What features have the greatest importance when classifying autistic individuals?

The data set for this topic is named *Autism-Adult-Data.arff*, a collection of ten behavioral questions and ten characteristics of individuals, each of which have been proven effective in detecting Autism Spectrum Disorder.

\pagebreak

## Research Topic 2

Our second research topic is on climate. Climate data includes the state of the atmosphere, such as temperature, precipitation, and wind speed, which can be used to examine weather patterns across various geographic regions and conduct time-series analysis to make predictions. By investigating this topic, we can better understand how our planet’s climate is changing, what factors are associated with the change, and potentially how we can mitigate climate change impacts.

Potential research questions include:

How does the total installed capacity of solar, wind, hydro, geothermal, and biomass power in a region affect its risk for severe weather events?

How do land use patterns and precipitation amounts affect ocean acidification in the U.S.?

How do the meteorological data help us predict the frequency, intensity, and geographic distribution of large-scale forest fires in the western U.S.?

Here are some ideas about the type of data: air temperature, precipitation, sea surface temperature, sea level, wind speed, atmospheric CO2 concentration, the frequency of severe weather events in a year, the pH of seawater, and the amount of carbon dioxide in the water. 

\pagebreak

## Research Topic 3

Our third research topic could be for stock price prediction. The motivation for this topic is that it's a common real-world application of regression analysis – there tend to be underlying patterns to stock prices and lots of relationships with other variables, and it's a quantitative variable that we can predict via these models. Potential audiences include any potential investors of the stock – whether that's a firm or an uninformed individual. Some potential questions include:

How well do interest rates predict the stock price movements of the technology sector?

How can a company's price-to-earnings and debt-to-equity ratios and return on equity influence their monthly stock price returns?

What is the relationship between foreign exchange rate fluctuations and stock price movements of multinational corporations in the S&P 500?

NASDAQ offers historical data to work with, and there are also plenty of data sets available through the Federal Reserve Bank of St. Louis and Yahoo Finance. Data is generally quite accessible for this general topic of stock prices, but may require merging for other features, like foreign exchange rate fluctuations for example.
