---
title: "Written Report on Factors that Help Diagnose Autism"
author: "The Repos - Jeffrey Bohrer, Alexandra Green, Anna Zhang, Kevin Lee"
date: "March 20, 2025"
format: pdf
execute: 
  warning: false
  message: false
  echo: false
editor: visual
---

```{r}
#| label: load packages and data

library(tidyverse)
library(tidymodels)
library(patchwork)
autism_ds <- read_csv("data/autism_ds.csv") %>%
  mutate(ethnicity = ifelse(ethnicity == "others", "Others", ethnicity))
```

Your written report goes here!

## Exploratory data analysis

**Univariate EDA**

```{r}
summary(autism_ds$result)

autism_ds |>
  ggplot(aes(x = result)) +
  geom_bar() +
  scale_x_continuous(breaks = seq(0, 10, 1), 
                     labels = as.character(seq(0, 10, 1))) +
  labs(x = "Score",
       y = "Count",
       title = "Histogram of Scoring Result")

autism_ds |>
  ggplot(aes(x = `Class/ASD`)) +
  geom_bar() +
  labs(x = "Test Result",
       y = "Count",
       title = "Distribution of Whether or not Result Indicative of Autism")
```

```{r}
autism_ds |>
  ggplot(aes(x = ethnicity)) +
  geom_bar() +
  labs(x = "Ethnicity",
       y = "Count",
       title = "Distribution of Ethnicity in the Dataset") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
autism_ds |>
  ggplot(aes(x = age)) +
  geom_bar() +
  labs(x = "Age",
       y = "Count",
       title = "Distribution of Age in the Dataset") +
  xlim(10, 75)

autism_ds |>
  ggplot(aes(x = `i_can_go_back_to_work_when_interrupted`)) +
  geom_bar() +
  labs(x = "Whether or not continue working after interrupted",
       y = "Count",
       title = "Distribution of the Ability to Return to Work after Interruption in the Dataset")
```

**Bivariate EDA**

```{r}
### Result score distributions by ethnicity
ggplot(autism_ds, 
       aes(x = result,
           y = ethnicity,
           fill = ethnicity)) +
  geom_boxplot() +
  labs(
    title = "Distribution of Scores Across Ethnicity",
    x = "Score",
    y = "Ethnicity"
  ) +
  theme_gray()

ggplot(autism_ds, 
       aes(x = result,
           y = relation,
           fill = relation)) +
  geom_violin(alpha = 0.5) +
  labs(
    title = "Distribution of Scores Across Person Filling Test",
    x = "Score",
    y = "Relation",
    fill
  ) +
  theme_gray()

Q1 <- ggplot(autism_ds, 
       aes(x = small_sounds,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q1",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q2 <- ggplot(autism_ds, 
       aes(x = difficult_to_understand_char,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q2",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q3 <- ggplot(autism_ds, 
       aes(x = ease_to_read_between_lines,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q3",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q4 <- ggplot(autism_ds, 
       aes(x = focus_on_whole_picture,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q4",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q5 <- ggplot(autism_ds, 
       aes(x = i_can_tell_if_someone_bored,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q5",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q6 <- ggplot(autism_ds, 
       aes(x = i_can_multi_task,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q6",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q7 <- ggplot(autism_ds, 
       aes(x = i_can_tell_feelings_from_faces,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q7",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()
Q8 <- ggplot(autism_ds, 
       aes(x = i_can_go_back_to_work_when_interrupted,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q8",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()
Q9 <- ggplot(autism_ds, 
       aes(x = i_like_to_collect_info_on_categories,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q9",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q10 <- ggplot(autism_ds, 
       aes(x = i_find_it_hard_to_figure_out_others_intentions,
           y = gender,
           fill = gender)) +
  geom_violin() +
  labs(
    title = "Q10",
    x = "Score",
    y = "Gender"
  ) +
  theme_gray()

Q1
Q2
Q3
Q4
Q5
Q6
Q7
Q8
Q9
Q10

ggplot(autism_ds |> filter(age < 200), aes(
  x = age,
  y = result
)) +
  geom_point() +
  labs(
    title = "Points in Test vs. Age",
    x = "Age",
    y = "Score"
  ) +
  theme_gray()

```

::: callout-important
Before you submit, make sure your code chunks are turned off with `echo: false` and there are no warnings or messages with `warning: false` and `message: false` in the YAML.
:::
